"""Changing set question relation

Revision ID: 6aceb0be425d
Revises: 8f90d51524a3
Create Date: 2021-06-07 11:10:16.514402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aceb0be425d'
down_revision = '8f90d51524a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set_questions', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_questions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
