"""Refactoring incorrect answers

Revision ID: bdec27f011c8
Revises: f48fa6d60743
Create Date: 2021-06-02 19:49:30.760039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdec27f011c8'
down_revision = 'f48fa6d60743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('incorrect_answer_1', sa.String(length=255), nullable=False))
    op.add_column('questions', sa.Column('incorrect_answer_2', sa.String(length=255), nullable=False))
    op.add_column('questions', sa.Column('incorrect_answer_3', sa.String(length=255), nullable=False))
    op.drop_column('questions', 'incorrect_answers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('incorrect_answers', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=False))
    op.drop_column('questions', 'incorrect_answer_3')
    op.drop_column('questions', 'incorrect_answer_2')
    op.drop_column('questions', 'incorrect_answer_1')
    # ### end Alembic commands ###
