"""Adding difficulty to question

Revision ID: 59208d88b775
Revises: 29064f2e988d
Create Date: 2021-06-02 10:05:09.866193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59208d88b775'
down_revision = '29064f2e988d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('difficulty', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'difficulty')
    # ### end Alembic commands ###
