"""empty message

Revision ID: 8f90d51524a3
Revises: bdec27f011c8
Create Date: 2021-06-02 23:42:57.295607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f90d51524a3'
down_revision = 'bdec27f011c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_comments', 'updated_at')
    # ### end Alembic commands ###
